### ISSUE TITLE
Ignore build directory when scanning for models

### ISSUE THREAD

**Issue by mtdowling** [smithy-lang/smithy-vscode#59]
It looks like we're including the build directory when loading the semantic model. We should ignore the build directory since it will have duplicate shapes and could have conflicting shapes when  using things like projections. For example, this shows up in the logs:

```[2022-10-11 12:12:30.729] [renderer1] [error] [Extension Host] stderr: Oct 11, 2022 12:12:30 PM software.amazon.smithy.model.loader.LoaderShapeMap validateConflicts
WARNING: Ignoring duplicate but equivalent shape definition: smithy.example#Post defined at /Users/x/projects/smithy-demo-model/build/smithy/source/sources/post.smithy [4, 1] and /Users/x/projects/smithy-demo-model/model/post.smithy [4, 1]
```

One negative effect of not filtering out the build directory is that you can get validation warnings that a previously built model conflicts with the model in your IDE. For example, build the model using the CLI or Gradle, then edit a member to target a different shape, and the IDE will tell you that the member in the IDE conflicts with the member in the build output.

**Comment by eduardomourar** [comment]
This would be really useful for us. And we are just using the default build folder.

**Comment by milesziemer** [comment]
Fixed in https://github.com/smithy-lang/smithy-vscode/releases/tag/0.6.0
